apiVersion: route.openshift.io/v1
kind: Route
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: billing-service
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: billing-service
    app.kubernetes.io/part-of: nyc-transit
  name: billing-service
  namespace: jduimovich
spec:
  port:
    targetPort: 8081
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: billing-service
    weight: 100
status: {}
